Feature: Historiske Dokumenter API Integration Test

  Background:
    * url url

  Scenario: Get all herredsnavn ASC

    Given path '/metadata/herredsnavn'
    When method get
    Then status 200

    # should be an array of strings with size 10
    # https://karatelabs.github.io/karate/#schema-validation
    And match response == '#array'
    And match response contains only
    """
    [
        "Aars",
        "Alsted",
        "Anst",
        "Ars",
        "Bjerge",
        "Bjæverskov",
        "Bornholms Nørre , Vester, Sønder og Øster Herred",
        "Bornholms Øster,  Nørre og Vester Herred",
        "Brusk",
        "Båg",
        "Bårse",
        "Bølling",
        "Børglum",
        "Djurs Nørre",
        "Djurs Sønder",
        "Dronninglund",
        "Elbo",
        "Fakse",
        "Falsters Nørre",
        "Falsters Sønder",
        "Fjends",
        "Fleskum",
        "Framlev",
        "Fuglse",
        "Galten",
        "Gerlev",
        "Gern",
        "Ginding",
        "Gislum",
        "Gudme",
        "Gørding",
        "Hads",
        "Hammer",
        "Hammerum",
        "Harre",
        "Hasle",
        "Hassing",
        "Hatting",
        "Hellum",
        "Hids",
        "Hilleslev",
        "Hind",
        "Hindborg",
        "Hindsted",
        "Hjelmslev",
        "Hjerm",
        "Holbo",
        "Holmans",
        "Horns",
        "Hornum",
        "Houlbjerg",
        "Hundborg",
        "Hvetbo",
        "Jerlev",
        "Kolding",
        "Kær",
        "Langelands Nørre",
        "Langelands Sønder",
        "Lollands Nørre",
        "Lollands Sønder",
        "Lunde",
        "Lynge-Frederiksborg",
        "Lynge-Kronborg",
        "Lysgård",
        "Læsø",
        "Løve",
        "Malt",
        "Merløse",
        "Middelsom",
        "Mols",
        "Morsø Nørre",
        "Morsø Sønder",
        "Musse",
        "Mønbo",
        "Nim",
        "Ning",
        "Nr. Horne",
        "Nørhald",
        "Nørlyng",
        "Nørre Herred",
        "Nørvang",
        "Odense",
        "Ods",
        "Onsild",
        "Ramsø",
        "Refs",
        "Ribe",
        "Rinds",
        "Ringsted",
        "Rovsø",
        "Rødding",
        "Sabro",
        "Salling Nørre",
        "Sallinge",
        "Samsø",
        "Skads",
        "Skam",
        "Skippinge",
        "Skodborg",
        "Skovby",
        "Slagelse",
        "Slavs",
        "Slet",
        "Smørum",
        "Sokkelund",
        "Stevns",
        "Strø",
        "Støvring",
        "Sunds",
        "Sømme",
        "Sønder Herred",
        "Sønderhald",
        "Sønderlyng",
        "Tune",
        "Tuse",
        "Tybjerg",
        "Tyrsting",
        "Tørrild",
        "Ulfborg",
        "Vandfuld",
        "Vends",
        "Vennebjerg",
        "Vester Flakkebjerg",
        "Vester Han",
        "Vester Herred",
        "Vester Horne",
        "Vester Lisbjerg",
        "Vindinge",
        "Voer",
        "Volborg",
        "Vrads",
        "Åsum",
        "Ærø",
        "Ølstykke",
        "Øster Flakkebjerg",
        "Øster Han",
        "Øster Herred",
        "Øster Horne",
        "Øster Lisbjerg"
    ]
    """
