package dk.dataforsyningen.arkivmeta.enums;

public enum Arketype {
  AELDRETOPOGRAFISKEKORT,
  CENTIMETERKORT,
  FAEROESKETOPOKORT,
  GROENLANDTOPOKORT,
  HISTORISKEFLYFOTO,
  LANDOEKONOMISKEKORT,
  MAALEBORDSBLADE,
  MATRIKELKORT,
  SOEKORT,
  TEMATISKEKORT;
}
