###
# daekningsomraade=Grønland&maalestok=1:250000
GET {{api_baseurl}}/kort?daekningsomraade=Grønland&maalestok=1:250000
token: {{token}}

###
# maalestok=1:250000&limit=25&offset=0&sort=titel&direction=asc
GET {{api_baseurl}}/kort?maalestok=1:250000&limit=25&offset=0&sort=titel&direction=asc
token: {{token}}

###
# multiple daekningsomraade
GET {{api_baseurl}}/kort?daekningsomraade=Slesvig&daekningsomraade=Danmark&titel=Haderslev i Frøs amt(er)
token: {{token}}

###
# tegner=bille
GET {{api_baseurl}}/kort?tegner=bille
token: {{token}}

###
# kortvaerk=Selskab
GET {{api_baseurl}}/kort?kortvaerk=Selskab
token: {{token}}

###
# fritekstsoegning=Sønderjylland
GET {{api_baseurl}}/kort?fritekstsoegning=Sønderjylland
token: {{token}}

###
# gaeldendeperiode_gaeldendefra=2000&gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendefra&direction=asc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendefra=2000&gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendefra&direction=asc
token: {{token}}

###
# Test kald for kortgrupper med kortværker
GET {{api_baseurl}}/metadata/kortgrupper/kortvaerker
Accept: application/json
token: {{token}}

###
# fritekstsoegning=Sønderjylland&sort=kortgruppe&direction=desc
GET {{api_baseurl}}/kort?fritekstsoegning=Sønderjylland&sort=kortgruppe&direction=desc
token: {{token}}

###
# kortgruppe=soekort&kortgruppe=centimeterkort&direction=asc&gaeldendeperiode_gaeldendefra=-1&gaeldendeperiode_gaeldendetil=-1&offset=0&limit=100&sort=kortgruppe
GET {{api_baseurl}}/kort?kortgruppe=soekort&kortgruppe=centimeterkort&direction=asc&gaeldendeperiode_gaeldendefra=-1&gaeldendeperiode_gaeldendetil=-1&offset=0&limit=100&sort=kortgruppe
token: {{token}}

###
# kortgruppe=soekort|centimeterkort&direction=desc&gaeldendeperiode_gaeldendefra=-1&gaeldendeperiode_gaeldendetil=-1&offset=0&limit=100&sort=kortgruppe
GET {{api_baseurl}}/kort?kortgruppe=soekort|centimeterkort&direction=desc&gaeldendeperiode_gaeldendefra=-1&gaeldendeperiode_gaeldendetil=-1&offset=0&limit=100&sort=kortgruppe
token: {{token}}

###
# kortgruppe=soekort&kortgruppe=centimeterkort&direction=asc&gaeldendeperiode_gaeldendefra=-1&gaeldendeperiode_gaeldendetil=-1&offset=0&limit=100
GET {{api_baseurl}}/kort?kortgruppe=soekort&kortgruppe=centimeterkort&direction=asc&gaeldendeperiode_gaeldendefra=-1&gaeldendeperiode_gaeldendetil=-1&offset=0&limit=100
token: {{token}}

###
# first character is uppercase daekningsomraade=Andre
GET {{api_baseurl}}/kort?daekningsomraade=Andre
token: {{token}}

###
# lowercase daekningsomraade=andre
GET {{api_baseurl}}/kort?daekningsomraade=andre
token: {{token}}

###
# kortgruppe=soekort&kortgruppe=centimeterkort&direction=desc&gaeldendeperiode_gaeldendefra=-1&gaeldendeperiode_gaeldendetil=-1&offset=0&limit=100&sort=kortgruppe
GET {{api_baseurl}}/kort?kortgruppe=soekort&kortgruppe=centimeterkort&direction=desc&gaeldendeperiode_gaeldendefra=-1&gaeldendeperiode_gaeldendetil=-1&offset=0&limit=100&sort=kortgruppe
token: {{token}}

###
# fritekstsoegning=Sønderjylland
GET {{api_baseurl}}/kort?fritekstsoegning=Sønderjylland
token: {{token}}

###
# kortgruppe=centimeterkort&gaeldendeperiode_gaeldendefra=2000&sort=gaeldendeperiode_gaeldendefra&direction=asc
GET {{api_baseurl}}/kort?kortgruppe=centimeterkort&gaeldendeperiode_gaeldendefra=2000&sort=gaeldendeperiode_gaeldendefra&direction=asc
token: {{token}}

###
# gaeldendeperiode_gaeldendefra=2000&sort=gaeldendeperiode_gaeldendefra&direction=desc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendefra=2000&sort=gaeldendeperiode_gaeldendefra&direction=desc
token: {{token}}

###
# gaeldendeperiode_gaeldendefra=2000&sort=gaeldendeperiode_gaeldendetil&direction=asc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendefra=2000&sort=gaeldendeperiode_gaeldendetil&direction=asc
token: {{token}}

###
# gaeldendeperiode_gaeldendefra=2000&sort=gaeldendeperiode_gaeldendetil&direction=desc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendefra=2000&sort=gaeldendeperiode_gaeldendetil&direction=desc
token: {{token}}

###
# gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendefra&direction=asc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendefra&direction=asc
token: {{token}}

###
# gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendefra&direction=desc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendefra&direction=desc
token: {{token}}

###
# gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendetil&direction=asc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendetil&direction=asc
token: {{token}}

###
# gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendetil&direction=desc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendetil&direction=desc
token: {{token}}

###
# gaeldendeperiode_gaeldendefra=1950&gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendefra&direction=asc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendefra=1950&gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendefra&direction=asc
token: {{token}}

###
# gaeldendeperiode_gaeldendefra=1950&gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendefra&direction=desc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendefra=1950&gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendefra&direction=desc
token: {{token}}

###
# gaeldendeperiode_gaeldendefra=1950&gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendetil&direction=asc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendefra=1950&gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendetil&direction=asc
token: {{token}}

###
# gaeldendeperiode_gaeldendefra=1950&gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendetil&direction=desc
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendefra=1950&gaeldendeperiode_gaeldendetil=2000&sort=gaeldendeperiode_gaeldendetil&direction=desc
token: {{token}}

###
# daekningsomraade=Slesvig|Danmark&sort=daekningsomraade&direction=desc
GET {{api_baseurl}}/kort?daekningsomraade=Slesvig|Danmark&sort=daekningsomraade&direction=desc
token: {{token}}

###
# Multiple arketyper kortgruppe=soekort&kortgruppe=centimeterkort
GET {{api_baseurl}}/kort?kortgruppe=soekort&kortgruppe=centimeterkort
token: {{token}}

###
# Multiple arketyper kortgruppe=soekort|centimeterkort
GET {{api_baseurl}}/kort?kortgruppe=soekort|centimeterkort
token: {{token}}

###
# Multiple kortvaerk kortvaerk=Trap, tegnede kort| Mejer
GET {{api_baseurl}}/kort?kortvaerk=Trap, tegnede kort| Mejer
token: {{token}}

###
# sort=titel&direction=asc
GET {{api_baseurl}}/kort?sort=titel&direction=asc
Accept: application/json
token: {{token}}

###
# kortgruppe=soekort&kortgruppe=centimeterkort&direction=desc&gaeldendeperiode_gaeldendefra=-1&gaeldendeperiode_gaeldendetil=-1&offset=0&limit=100&sort=kortgruppe&token={{token}}
GET {{api_baseurl}}/kort?kortgruppe=soekort&kortgruppe=centimeterkort&direction=desc&gaeldendeperiode_gaeldendefra=-1&gaeldendeperiode_gaeldendetil=-1&offset=0&limit=100&sort=kortgruppe&token={{token}}
token: {{token}}

###
# tegner=sørensen
GET {{api_baseurl}}/kort?tegner=sørensen
token: {{token}}

###
# gaeldendeperiode_gaeldendefra=1950&gaeldendeperiode_gaeldendetil=2000&kortgruppe=centimeterkort
GET {{api_baseurl}}/kort?gaeldendeperiode_gaeldendefra=1950&gaeldendeperiode_gaeldendetil=2000&kortgruppe=centimeterkort
token: {{token}}

###
# fritekstsoegning=Sønderjylland&sort=kortgruppe&direction=desc
GET {{api_baseurl}}/kort?fritekstsoegning=Sønderjylland&sort=kortgruppe&direction=desc
token: {{token}}

###
# historiskeflyfoto/73236
GET {{api_baseurl}}/kort/historiskeflyfoto/73236
Accept: application/json
token: {{token}}

###
# Ønskes returneret alle daekningsomraader
GET {{api_baseurl}}/metadata/daekningsomraader
Accept: application/json
token: {{token}}

###
# Ønskes returneret alle de daekningsomraader der har den specificeret søgning i sig
GET {{api_baseurl}}/metadata/daekningsomraader?daekningsomraade=sønderjylland
Accept: application/json
token: {{token}}

###
# Ønskes returneret alle maalestokke
GET {{api_baseurl}}/metadata/maalestok
Accept: application/json
token: {{token}}

###
# Ønskes returneret alle de maalestokke der har den specificeret søgning i sig
GET {{api_baseurl}}/metadata/maalestok?maalestok=200
Accept: application/json
token: {{token}}

###
# Test kald for post Java
POST {{api_baseurl}}/kort
token: {{token}}

###
# Test kald for post Java
POST {{api_baseurl}}/kort
Accept: application/json
Content-Type: application/json
token: {{token}}

{
    "daekningsomraade": ["Danmark", "Slesvig"],
    "limit": 100,
    "sort": "id",
    "direction": "asc"
}

###
# Test kald for post Kotlin
POST localhost:8087/kort
Accept: application/json
Content-Type: application/json
token: {{token}}
{
    "daekningsomraade": "Danmark",
    "sort": "id"
}

###
# Swagger UI dokumentationen JSON
GET {{api_baseurl}}/v3/api-docs
token: {{token}}

###
https://api.dataforsyningen.dk/rest/arkivkort/iiif/3/LzMxIC0gZGFubWFyayB0b3BvZ3JhZmkgY2VudGltZXRlcmtvcnQvMzEtNjMgMSBjbSBrb3J0IGZvcnN2YXJldC81MDgvZDEwMGZfTTYxMTNfRjZfMjAxNS5qcGVn/full/max/0/default.jpg
token: {{token}}

###
# Swagger UI dokumentation test miljø
GET {{api_baseurl}}/swagger-ui/index.html?configUrl=/rest/arkivmeta/v3/api-docs/swagger-config
token: {{token}}

###
# kortvaerk=Original 2, supplerende
GET {{api_baseurl}}/kort?kortvaerk=Original 2, supplerende
token: {{token}}

###
# Geometry call
GET {{api_baseurl}}/kort?geometri=POINT(12.226727129244841 55.86164621853605)&limit=25&offset=0&token=147df2cc622086861a8ca994809a1ace
token: {{token}}